### ISSUE TITLE
update sign in with github text

### ISSUE THREAD

**Issue by kvignali** [learn-co/learn-ide-3#9]
"Already have a GitHub account" copy logic. People *will* already have a Github account with the new flow. Change to "Or use your GitHub account"?

<img width="497" alt="screen shot 2017-09-20 at 12 46 33 pm" src="https://user-images.githubusercontent.com/2243896/30656356-d47c175a-9e01-11e7-8d9f-f685c39b092e.png">

**Comment by ktravers** [comment]
this view actually lives on ironboard repo. will PR from that project instead
